/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SignalsRouteImport } from './routes/signals'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ChartRouteImport } from './routes/chart'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicWebhooksClickpesaRouteImport } from './routes/api/public/webhooks/clickpesa'
import { Route as ApiPublicCronSlTpRouteImport } from './routes/api/public/cron/sl-tp'
import { Route as ApiPublicCronSignalsRouteImport } from './routes/api/public/cron/signals'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SignalsRoute = SignalsRouteImport.update({
  id: '/signals',
  path: '/signals',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ChartRoute = ChartRouteImport.update({
  id: '/chart',
  path: '/chart',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksClickpesaRoute =
  ApiPublicWebhooksClickpesaRouteImport.update({
    id: '/api/public/webhooks/clickpesa',
    path: '/api/public/webhooks/clickpesa',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronSlTpRoute = ApiPublicCronSlTpRouteImport.update({
  id: '/api/public/cron/sl-tp',
  path: '/api/public/cron/sl-tp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronSignalsRoute = ApiPublicCronSignalsRouteImport.update({
  id: '/api/public/cron/signals',
  path: '/api/public/cron/signals',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/chart': typeof ChartRoute
  '/login': typeof LoginRoute
  '/signals': typeof SignalsRoute
  '/signup': typeof SignupRoute
  '/wallet': typeof WalletRoute
  '/api/public/cron/signals': typeof ApiPublicCronSignalsRoute
  '/api/public/cron/sl-tp': typeof ApiPublicCronSlTpRoute
  '/api/public/webhooks/clickpesa': typeof ApiPublicWebhooksClickpesaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/chart': typeof ChartRoute
  '/login': typeof LoginRoute
  '/signals': typeof SignalsRoute
  '/signup': typeof SignupRoute
  '/wallet': typeof WalletRoute
  '/api/public/cron/signals': typeof ApiPublicCronSignalsRoute
  '/api/public/cron/sl-tp': typeof ApiPublicCronSlTpRoute
  '/api/public/webhooks/clickpesa': typeof ApiPublicWebhooksClickpesaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/chart': typeof ChartRoute
  '/login': typeof LoginRoute
  '/signals': typeof SignalsRoute
  '/signup': typeof SignupRoute
  '/wallet': typeof WalletRoute
  '/api/public/cron/signals': typeof ApiPublicCronSignalsRoute
  '/api/public/cron/sl-tp': typeof ApiPublicCronSlTpRoute
  '/api/public/webhooks/clickpesa': typeof ApiPublicWebhooksClickpesaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/chart'
    | '/login'
    | '/signals'
    | '/signup'
    | '/wallet'
    | '/api/public/cron/signals'
    | '/api/public/cron/sl-tp'
    | '/api/public/webhooks/clickpesa'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/chart'
    | '/login'
    | '/signals'
    | '/signup'
    | '/wallet'
    | '/api/public/cron/signals'
    | '/api/public/cron/sl-tp'
    | '/api/public/webhooks/clickpesa'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/chart'
    | '/login'
    | '/signals'
    | '/signup'
    | '/wallet'
    | '/api/public/cron/signals'
    | '/api/public/cron/sl-tp'
    | '/api/public/webhooks/clickpesa'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  ChartRoute: typeof ChartRoute
  LoginRoute: typeof LoginRoute
  SignalsRoute: typeof SignalsRoute
  SignupRoute: typeof SignupRoute
  WalletRoute: typeof WalletRoute
  ApiPublicCronSignalsRoute: typeof ApiPublicCronSignalsRoute
  ApiPublicCronSlTpRoute: typeof ApiPublicCronSlTpRoute
  ApiPublicWebhooksClickpesaRoute: typeof ApiPublicWebhooksClickpesaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signals': {
      id: '/signals'
      path: '/signals'
      fullPath: '/signals'
      preLoaderRoute: typeof SignalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chart': {
      id: '/chart'
      path: '/chart'
      fullPath: '/chart'
      preLoaderRoute: typeof ChartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/clickpesa': {
      id: '/api/public/webhooks/clickpesa'
      path: '/api/public/webhooks/clickpesa'
      fullPath: '/api/public/webhooks/clickpesa'
      preLoaderRoute: typeof ApiPublicWebhooksClickpesaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/sl-tp': {
      id: '/api/public/cron/sl-tp'
      path: '/api/public/cron/sl-tp'
      fullPath: '/api/public/cron/sl-tp'
      preLoaderRoute: typeof ApiPublicCronSlTpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/signals': {
      id: '/api/public/cron/signals'
      path: '/api/public/cron/signals'
      fullPath: '/api/public/cron/signals'
      preLoaderRoute: typeof ApiPublicCronSignalsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  ChartRoute: ChartRoute,
  LoginRoute: LoginRoute,
  SignalsRoute: SignalsRoute,
  SignupRoute: SignupRoute,
  WalletRoute: WalletRoute,
  ApiPublicCronSignalsRoute: ApiPublicCronSignalsRoute,
  ApiPublicCronSlTpRoute: ApiPublicCronSlTpRoute,
  ApiPublicWebhooksClickpesaRoute: ApiPublicWebhooksClickpesaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
